### ISSUE TITLE
Consider adding a PropertyWrapper to ValueBinders ？

### ISSUE THREAD

**Issue by Mx-Iris** [dagronf/DSFValueBinders#1]
I saw your AppKit DSL Library and it looks great. It would look more like SwiftUI if we could add a propertyWrapper to ValueBinder

**Comment by dagronf** [comment]
I've added your property wrapper changes to the 0.9.1 tag.

https://github.com/dagronf/DSFValueBinders/compare/0.8.3...0.9.1

Thank you!
